defmodule Emily.Grad.ExlaOracleTest do
  @moduledoc """
  EXLA gradient conformance (M13).

  Compares Emily.Compiler gradient output against golden values produced
  by EXLA (XLA CPU backend) for the same deterministic inputs. EXLA's
  HLO compiler and optimised kernels are a fundamentally different
  computation path from both `Nx.BinaryBackend` and MLX, providing an
  independent third opinion on gradient correctness.

  The M9 grad oracles (BinaryBackend symbolic grad and f32 finite
  differences) can be wrong in the same direction — BinaryBackend's
  symbolic grad is the same `Nx.Defn.grad` lowering Emily uses, so a
  bug in the lowering passes both. EXLA breaks that shared-fault mode.

  `grad_dropout` is excluded: MLX, BinaryBackend, and EXLA all use
  different PRNG implementations, so cross-backend gradient values for
  stochastic ops are not comparable. See `grad_equivalence_test.exs`
  PRNG-key threading section for Emily-internal determinism tests.

  Golden values generated by `bench/exla_golden_gen/` — see
  `test/support/exla_golden_data.ex` for provenance.
  """

  use ExUnit.Case, async: true

  import Emily.BackendGenerators, only: [to_emily: 1]

  alias Emily.ExlaGoldenData
  alias Emily.GradZoo
  alias Emily.TrainingHelper, as: TH

  @moduletag :grad_conformance

  # Per-function tolerance tables.
  #
  # Emily (MLX Metal) and EXLA (XLA CPU) use different kernels and
  # different reduction ordering, so exact bit-match isn't expected.
  # These tolerances were calibrated against EXLA 0.11.0 CPU goldens
  # on Apple Silicon.
  #
  # {atol, rtol} — comparison: |emily - exla| <= atol + rtol * |exla|
  @tolerance %{
    grad_sum_op: {1.0e-6, 1.0e-5},
    grad_dot_left: {1.0e-5, 1.0e-4},
    grad_reshape_transpose: {1.0e-6, 1.0e-5},
    grad_broadcast: {1.0e-6, 1.0e-5},
    grad_gather: {1.0e-6, 1.0e-5},
    grad_indexed_add: {1.0e-6, 1.0e-5},
    grad_gather_dot_softmax: {5.0e-5, 5.0e-4},
    grad_attention: {1.0e-4, 1.0e-3},
    block_step_loss: {1.0e-4, 1.0e-3},
    block_step_params: {1.0e-4, 1.0e-3}
  }

  @default_tolerance {1.0e-4, 1.0e-3}

  # -------------------- Zoo functions --------------------

  # Zoo entries without a pre-generated EXLA golden (e.g. the M17
  # window ops added after the last golden regen) skip here — their
  # correctness is covered by the BinaryBackend grad-equivalence test.
  # Run `mix run bench/exla_golden_gen.exs` to extend coverage.
  for name <- GradZoo.all_functions(), ExlaGoldenData.has_golden?(name) do
    describe "#{name}" do
      test "Emily grad matches EXLA golden" do
        name = unquote(name)
        inputs = GradZoo.fixed_inputs(name)
        fun = GradZoo.grad_function(name)
        golden = ExlaGoldenData.golden(name)

        emily_inputs = Enum.map(inputs, &to_emily/1)
        emily_result = Nx.Defn.jit_apply(fun, emily_inputs, compiler: Emily.Compiler)

        expected =
          Nx.tensor(golden.expected, type: golden.type, backend: Nx.BinaryBackend)
          |> Nx.reshape(golden.shape)

        assert_grad_close(emily_result, expected, name)
      end
    end
  end

  # -------------------- Transformer block training step --------------------

  describe "transformer block training step" do
    @embed 16
    @ff 32
    @seq 8
    @lr_val 0.1

    test "1-step loss and params match EXLA golden" do
      scale_val = 1.0 / :math.sqrt(@embed)
      golden = ExlaGoldenData.block_step_golden()

      params = TH.init_block({@embed, @ff}, 0, Emily.Backend)
      {x, y} = TH.block_batch({@seq, @embed}, Emily.Backend)
      lr = Nx.tensor(@lr_val, type: {:f, 32}, backend: Emily.Backend)
      scale = Nx.tensor(scale_val, type: {:f, 32}, backend: Emily.Backend)

      {new_params, loss} =
        Nx.Defn.jit_apply(
          &TH.block_step_with_loss/5,
          [params, x, y, lr, scale],
          compiler: Emily.Compiler
        )

      # Assert loss.
      loss_f = loss |> Nx.backend_transfer(Nx.BinaryBackend) |> Nx.to_number()
      {atol, rtol} = tolerance_for(:block_step_loss)

      assert abs(loss_f - golden.loss) <= atol + rtol * abs(golden.loss),
             "loss divergence: emily=#{loss_f} exla=#{golden.loss} " <>
               "diff=#{abs(loss_f - golden.loss)}"

      # Assert each parameter tensor.
      for key <- [:wq, :wk, :wv, :wo, :w_ff1, :b_ff1, :w_ff2, :b_ff2] do
        param_golden = golden.params[key]

        expected =
          Nx.tensor(param_golden.expected, type: param_golden.type, backend: Nx.BinaryBackend)
          |> Nx.reshape(param_golden.shape)

        assert_grad_close(new_params[key], expected, :block_step_params, label: "param #{key}")
      end
    end
  end

  # -------------------- Helpers --------------------

  defp tolerance_for(name) do
    Map.get(@tolerance, name, @default_tolerance)
  end

  defp assert_grad_close(actual, expected, name, opts \\ []) do
    {atol, rtol} = tolerance_for(name)
    label = opts[:label] || inspect(name)

    actual_bin = Nx.backend_transfer(actual, Nx.BinaryBackend)
    expected_bin = Nx.backend_transfer(expected, Nx.BinaryBackend)

    if actual_bin.shape != expected_bin.shape do
      flunk(
        "#{label}: shape mismatch: #{inspect(actual_bin.shape)} vs #{inspect(expected_bin.shape)}"
      )
    end

    actual_list = Nx.to_flat_list(actual_bin)
    expected_list = Nx.to_flat_list(expected_bin)

    mismatches =
      actual_list
      |> Enum.zip(expected_list)
      |> Enum.with_index()
      |> Enum.reject(fn {{a, e}, _i} -> abs(a - e) <= atol + rtol * abs(e) end)
      |> Enum.take(5)

    if mismatches != [] do
      details =
        Enum.map_join(mismatches, "\n  ", fn {{a, e}, i} ->
          "[#{i}] emily=#{inspect(a)} exla=#{inspect(e)} diff=#{inspect(abs(a - e))}"
        end)

      flunk("""
      #{label}: Emily grad diverged from EXLA golden (atol=#{atol}, rtol=#{rtol})
        #{details}
      """)
    end
  end
end
